export const mockIndicateurs = [
  { id: '1', categorie: 'food',      nom: 'Café arabica',      valeur: 5.34,  unite: '€/livre',   variation_pct:  11.2, source: 'ICE NY',        semaine: 21, annee: 2026 },
  { id: '2', categorie: 'food',      nom: 'Bœuf haché 15%',    valeur: 7.85,  unite: '€/kg',      variation_pct:   4.7, source: 'FranceAgriMer', semaine: 21, annee: 2026 },
  { id: '3', categorie: 'food',      nom: 'Cacao brut',         valeur: 6840,  unite: '€/tonne',   variation_pct:  -5.2, source: 'ICE',           semaine: 21, annee: 2026 },
  { id: '4', categorie: 'food',      nom: 'Lait entier',        valeur: 415,   unite: '€/1 000 L', variation_pct:   3.1, source: 'Atla',          semaine: 21, annee: 2026 },
  { id: '5', categorie: 'food',      nom: 'Farine T55',         valeur: 28.5,  unite: '€/quintal', variation_pct:   0,   source: 'Matif',         semaine: 21, annee: 2026 },
  { id: '6', categorie: 'food',      nom: 'Huile tournesol',    valeur: 1120,  unite: '€/tonne',   variation_pct:  -2.8, source: 'Matif',         semaine: 21, annee: 2026 },
  { id: '7', categorie: 'energie',   nom: 'Électricité spot',   valeur: 82.4,  unite: '€/MWh',     variation_pct:  -6.1, source: 'EPEX',          semaine: 21, annee: 2026 },
  { id: '8', categorie: 'boissons',  nom: 'Vin rosé Provence',  valeur: 3.2,   unite: '€/litre',   variation_pct:   1.4, source: 'FranceAgriMer', semaine: 21, annee: 2026 },
  { id: '9',  categorie: 'boissons',  nom: 'Bière houblon',           valeur: 2.8,   unite: '€/litre', variation_pct:  2.1, source: 'Eurostat',          semaine: 21, annee: 2026 },
  { id: '10', categorie: 'juridique', nom: 'SMIC horaire CHR',          valeur: 12.08, unite: '€/h',     variation_pct:  0.6, source: 'Journal Officiel',  semaine: 21, annee: 2026 },
  { id: '11', categorie: 'juridique', nom: 'ILC — Indice Loyers Com.',  valeur: 135.7, unite: 'pts',     variation_pct:  2.1, source: 'INSEE',             semaine: 21, annee: 2026 },
  { id: '12', categorie: 'juridique', nom: 'TVA restauration',          valeur: 10,    unite: '%',       variation_pct:  0,   source: 'DGFiP',             semaine: 21, annee: 2026 },
  { id: '13', categorie: 'juridique', nom: 'Taux intérêt légal',        valeur: 5.07,  unite: '%',       variation_pct: -0.8, source: 'Banque de France',  semaine: 21, annee: 2026 },
  { id: '14', categorie: 'juridique', nom: 'Cotisations patronales CHR',valeur: 44.2,  unite: '%',       variation_pct:  0,   source: 'URSSAF',            semaine: 21, annee: 2026 },
  { id: '15', categorie: 'rh',       nom: 'SMIC horaire net CHR',      valeur: 9.50,  unite: '€/h',     variation_pct:  0.6, source: 'Ministère Travail', semaine: 21, annee: 2026 },
  { id: '16', categorie: 'rh',       nom: 'Turnover annuel CHR',       valeur: 84,    unite: '%',       variation_pct:  3.2, source: 'UMIH',              semaine: 21, annee: 2026 },
  { id: '17', categorie: 'rh',       nom: 'Coût horaire moyen CHR',    valeur: 16.4,  unite: '€/h',     variation_pct:  1.8, source: 'Dares',             semaine: 21, annee: 2026 },
  { id: '18', categorie: 'rh',       nom: 'Offres d\'emploi CHR',      valeur: 42800, unite: 'offres',  variation_pct: -2.1, source: 'Pôle Emploi',      semaine: 21, annee: 2026 },
  { id: '19', categorie: 'rh',       nom: 'Absentéisme CHR',           valeur: 6.8,   unite: '%',       variation_pct:  0.4, source: 'Malakoff Humanis', semaine: 21, annee: 2026 },
]

export const mockSignaux = [
  {
    id: '1',
    titre: "Sécheresse Côte d'Ivoire — tension cacao",
    description: "GDELT détecte une intensification médiatique +38% sur 7j. Probabilité de hausse élevée dans 4–6 semaines.",
    zone: "Côte d'Ivoire",
    produits_lies: ['cacao'],
    impact: 'hausse',
    horizon: '4–6 semaines',
    source: 'GDELT',
    positive: false,
  },
  {
    id: '2',
    titre: "Tensions Mer Rouge — épices et riz",
    description: "Détournements maritimes actifs. Routes Asie-Europe allongées de 10–14 jours.",
    zone: "Mer Rouge",
    produits_lies: ['épices', 'riz'],
    impact: 'hausse',
    horizon: 'Surveillance active',
    source: 'GDELT',
    positive: false,
  },
  {
    id: '3',
    titre: "Brésil café — stabilisation probable",
    description: "Pluies annoncées zone arabica. Signal de détente dans 3–4 semaines.",
    zone: "Brésil",
    produits_lies: ['café'],
    impact: 'baisse',
    horizon: '3–4 semaines',
    source: 'GDELT',
    positive: true,
  },
]

export const mockAlertes = [
  {
    id: '1',
    type: 'surcout',
    titre: "Café arabica — seuil de +10% franchi",
    description: "Votre seuil d'alerte personnalisé a été déclenché. Voir signaux géopolitiques Brésil.",
    severite: 'high',
    lu: false,
    time_display: "Aujourd'hui",
  },
  {
    id: '2',
    type: 'reglementation',
    titre: "SMIC horaire revalorisé au 01/05 — grilles HCR à mettre à jour",
    description: "Nouveau taux : 12,08 €/h. Convention collective HCR (IDCC 1979) impactée dès juin 2026. Source : Légifrance.",
    severite: 'medium',
    lu: false,
    time_display: "01/05",
  },
  {
    id: '3',
    type: 'reglementation',
    titre: "Décret affichage prix cartes — applicable le 01/09/2026",
    description: "Mention TTC et TVA distincte obligatoire sur les menus. Délai de mise en conformité : 15 semaines. Source : Légifrance / JO.",
    severite: 'low',
    lu: false,
    time_display: "Sem. 18",
  },
  {
    id: '4',
    type: 'reglementation',
    titre: "Allergènes : mise à jour liste obligatoire en salle",
    description: "Arrêté du 30/04/2026 : les 14 allergènes majeurs doivent être mentionnés sur support écrit disponible à la demande. Applicable immédiatement. Source : Légifrance.",
    severite: 'medium',
    lu: false,
    time_display: "Sem. 19",
  },
  {
    id: '5',
    type: 'reglementation',
    titre: "ERP restauration : obligation de défibrillateur au 01/07/2026",
    description: "Décret n°2026-412 : les ERP de catégorie 1 à 4 dont les restaurants > 300 couverts doivent installer un DAE accessible. Délai : 6 semaines. Source : Légifrance.",
    severite: 'medium',
    lu: false,
    time_display: "Sem. 20",
  },
]

export const tickerItems = [
  { name: 'Café arabica',       value: '5,34 €',       change: '+11,2%', up: true },
  { name: 'Cacao',              value: '6 840 €/t',    change: '−5,2%',  up: false },
  { name: 'Électricité spot',   value: '82,40 €/MWh',  change: '−6,1%',  up: false },
  { name: 'Bœuf haché',         value: '7,85 €/kg',    change: '+4,7%',  up: true },
  { name: 'Indice panier CHR',  value: '124,3',         change: '+2,1%',  up: true },
  { name: 'Lait entier',        value: '415 €/kL',     change: '+3,1%',  up: true },
  { name: 'Farine T55',         value: '28,50 €/qtx',  change: 'stable', up: null },
  { name: 'Huile tournesol',    value: '1 120 €/t',    change: '−2,8%',  up: false },
]
